### ISSUE TITLE
nothing 

### ISSUE THREAD

**Issue by papagodzilla** [DRCRecoveryData/JPEG-Repair-Tool#1]
just clone repo and double click but nothing comes up and when try to move folder it say it ruuning. 
and honestly i have no idea what to do after searching solution for half an hour

**Comment by DRCRecoveryData** [comment]
> just clone repo and double click but nothing comes up and when try to move folder it say it ruuning. 
> 
> and honestly i have no idea what to do after searching solution for half an hour

You need install lastest python then install requirements:

```pip install pyqt6 numpy pillow```

**Comment by papagodzilla** [comment]
![Untitled2](https://github.com/user-attachments/assets/548cfe1c-be59-4f38-a190-0d100fec17d3)
already done i have using other repo so its already satisfied requirments

**Comment by DRCRecoveryData** [comment]
> 
> 
> ![Untitled2](https://github.com/user-attachments/assets/548cfe1c-be59-4f38-a190-0d100fec17d3)
> 
> already done i have using other repo so its already satisfied requirments 

So which is your error? It's run normal in here

**Comment by papagodzilla** [comment]
nothing come up just a window for micro second and done no cpu usage in task manager nothing

do you run by python file.py?

**Comment by papagodzilla** [comment]
> nothing come up just a window for micro second and done no cpu usage in task manager nothing
> 
> do you run by python file.py?

yes multiple times even restart pc too

**Comment by DRCRecoveryData** [comment]
It's run normal in here maybe you install python wrong

**Comment by DRCRecoveryData** [comment]
Installation:

https://youtu.be/f7HLrJwjwhk
